FROM ubuntu:18.04 AS builder

LABEL maintainer="Ian Rambo" email="ian.rambo@utexas.edu"

USER root

RUN apt-get update && apt-get install -y apt-utils \
    software-properties-common \
    build-essential \
    wget \
    git \
    unzip \
    gcc \
    make \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN mkdir -p /build

ARG USER_ID
ARG GROUP_ID

#RUN addgroup --gid $GROUP_ID crispr
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID crispr

#RUN groupadd -r crispr && useradd -r -s /bin/sh -g crispr crispr


WORKDIR /build

RUN wget -q https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.10.0+-x64-linux.tar.gz \
    && tar -zxf ncbi-blast-2.10.0+-x64-linux.tar.gz \
    && rm ncbi-blast-2.10.0+-x64-linux.tar.gz \
    && git clone https://github.com/davidchyou/CRISPRDetect_2.4.git \
    && cd CRISPRDetect_2.4 \
    && unzip CRISPRDetect_2.4.zip \
    && rm CRISPRDetect_2.4.zip \
    && cp /build/ncbi-blast-2.10.0+/bin/blastn /build/CRISPRDetect_2.4/CRISPRDetect_2.4 \
    && rm -rf /build/ncbi-blast-2.10.0+

COPY ./bin /build/bin

#RUN chown -R crispr:crispr /build \
RUN chown -R crispr:$GROUP_ID /build \
    && chmod -R 755 /build/CRISPRDetect_2.4/CRISPRDetect_2.4 \
    && chmod -R 777 /build/CRISPRDetect_2.4/CRISPRDetect_2.4/tmp \
    && chmod -R 755 /build/bin

USER crispr

FROM ubuntu:18.04

USER root

ARG USER_ID
ARG GROUP_ID

RUN apt-get update && apt-get install -y apt-utils \
    build-essential \
    gcc \
    make \
    cpanminus \
    python3 \
    python3-pip \
    cd-hit \
    prodigal \
    less \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean \
    && pip3 install biopython pandas python-magic

#RUN groupadd -r crispr && useradd -r -s /bin/sh -g crispr crispr

#RUN addgroup --gid $GROUP_ID crispr
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID crispr

RUN cpanm Parallel::ForkManager

#COPY --from=builder --chown=crispr:crispr /build /build
COPY --from=builder --chown=crispr:$GROUP_ID /build /build

USER crispr

ENV PATH "$PATH:/build/CRISPRDetect_2.4/CRISPRDetect_2.4:/build/bin"
