FROM ubuntu:18.04 AS build

LABEL maintainer="ian.rambo@utexas.edu"

USER root

RUN apt-get update && apt-get install -y wget \
    git \
    unzip \
    gcc \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

RUN mkdir -p /build

RUN groupadd -r crispr && useradd -r -s /bin/sh -g crispr crispr

RUN cpan upgrade Test::More \
    && cpan Parallel::ForkManager

WORKDIR /build

# Install blastn and CRISPRDetect 2.4
RUN wget -q https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.10.0+-x64-linux.tar.gz \
    && tar -zxf ncbi-blast-2.10.0+-x64-linux.tar.gz \
    && rm ncbi-blast-2.10.0+-x64-linux.tar.gz \
    && git clone https://github.com/davidchyou/CRISPRDetect_2.4.git \
    && cd CRISPRDetect_2.4 \
    && unzip CRISPRDetect_2.4.zip \
    && rm CRISPRDetect_2.4.zip \
    && cd CRISPRDetect_2.4 \
    && cp /build/ncbi-blast-2.10.0+/bin/blastn . \
    && chown -R crispr:crispr /build \
    && chown -R crispr:crispr . \
    && chown -R crispr:crispr tmp \
    && rm -rf /build/ncbi-blast-2.10.0+

#USER crispr

COPY ./test /build/test

#FROM alpine:3.11.6

#RUN apk update && apk --no-cache add perl

#RUN addgroup -S crispr && adduser -S crispr -G crispr -s /bin/sh

#USER crispr

#COPY --from=build --chown=crispr:crispr /build /build

#ENV PATH "$PATH:/build/CRISPRDetect_2.4/CRISPRDetect_2.4"
