FROM ubuntu:18.04

LABEL maintainer="ian.rambo@utexas.edu"


RUN apt-get update && apt-get install -y apt-utils \
    default-jdk \
    zlib1g-dev \
    default-jre \
    software-properties-common \
    libdb-dev \
    python3-pip \
    git \
    ncbi-blast+ \
    prodigal \
    autoconf \
    automake \
    libtool \
    gcc \
    make \
    cmake \
    g++ \
    unzip \
    libstdc++6 \
    libgomp1 \
    libpcre3 \
    libpcre3-dev \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean


RUN pip3 install biopython pandas python-magic

RUN mkdir -p /build/bin
WORKDIR /build

#CRISPRDetect_2.4
RUN git clone https://github.com/davidchyou/CRISPRDetect_2.4.git \
    && cd CRISPRDetect_2.4 \
    && unzip CRISPRDetect_2.4.zip \
    && rm CRISPRDetect_2.4.zip \
    && cpan Parallel::ForkManager \
    && cd CRISPRDetect_2.4 \
    && chmod -R 755 . && chmod 777 tmp

ENV PATH "$PATH:/build/CRISPRDetect_2.4/CRISPRDetect_2.4"

COPY ./bin /build/bin
