FROM ubuntu:18.04 AS stage1

LABEL maintainer="ian.rambo@utexas.edu"

USER root

RUN mkdir -p /build/data /build/dep

RUN apt-get update && apt-get -y install apt-utils \
    software-properties-common \
    build-essential \
    wget \
    gcc \
    make \
    python3 \
    python2.7 \
    python-pip \
    git \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean -y \
    && pip install coverage python-coveralls

RUN groupadd -r macsygrp && useradd -r -s /bin/nologin -g macsygrp macsygrp

WORKDIR /build

RUN wget http://eddylab.org/software/hmmer/hmmer.tar.gz \
    && tar -zxf hmmer.tar.gz \
    && cd hmmer-3.3 \
    && ./configure --prefix /build \
    && make \
    && make check \
    && make install \
    && rm /build/hmmer.tar.gz \
    && cp /build/hmmer-3.3/src/hmmsearch /build/dep \
    && cd /build \
    && rm -rf /build/hmmer-3.3

RUN wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ncbi-blast-2.10.0+-x64-linux.tar.gz \
    && tar -zxf ncbi-blast-2.10.0+-x64-linux.tar.gz \
    && rm ncbi-blast-2.10.0+-x64-linux.tar.gz \
    && cp /build/ncbi-blast-2.10.0+/bin/makeblastdb /build/dep \
    && rm -rf /build/ncbi-blast-2.10.0+

ENV PATH "$PATH:/build/dep"

RUN wget https://bintray.com/gem-pasteur/MacSyFinder/download_file?file_path=macsyfinder-1.0.5.tar.gz -O macsyfinder-1.0.5.tar.gz \
    && tar -zxf macsyfinder-1.0.5.tar.gz \
    && cd macsyfinder-1.0.5 \
    && python2.7 setup.py build \
    && python2.7 setup.py test -vv \
    && python2.7 setup.py install --no-viewer \
    && cd .. \
    && rm macsyfinder-1.0.5.tar.gz

#RUN git clone https://github.com/gem-pasteur/macsyfinder.git \
#    && cd macsyfinder \
#    && python2.7 setup.py build \
#    && python2.7 setup.py test -vv \
#    && python2.7 setup.py install

RUN chown -R macsygrp:macsygrp /build

USER macsygrp

FROM python:2.7.18-alpine3.11

USER root

RUN addgroup -S macsygrp && adduser -S macsygrp -G macsygrp

RUN pip install coverage python-coveralls

USER macsygrp

COPY --from=stage1 --chown=macsygrp:macsygrp /build /build

ENV PATH "$PATH:/build/dep:/build/macsyfinder-1.0.5/bin:/build/macsyfinder-1.0.5/macsypy:/build/macsyfinder-1.0.5/macsyview"

#ENTRYPOINT ["macsyfinder"]

#CMD ["-h"]
