Import('env')

import os
import logging
import re
import pandas as pd
"""
Motivation: dereplication, clusting, and alignment for phylogenetic trees.
Iterative approach for RNA viruses
Author: Ian Rambo
"""

logging_format = '%(levelname)s %(asctime)s - $(message)s'
logging.basicConfig(filename = 'joblog', level = logging.DEBUG, format = logging_format)
logger = logging.getLogger()
#------------------------------------------------------------------------------
def check_string(source):
    """
    Check if string is binary (return True) or not (return False)
    """
    p = set(source)
    s = {'0', '1'}

    if s == p or p == {'0'} or p == {'1'}:
        return True
    else :
        return False
#------------------------------------------------------------------------------
def GET_BASENAME(file_path):
    """
    Get the basename of a file and remove all extensions
    """
    if check_string(file_path):
        file_path = file_path.decode('ascii')
    else:
        pass
    basename = os.path.basename(file_path)
    #Remove two extensions, e.g. foo.tar.gz becomes foo
    if re.match(r'^.*?\.[a-z]+\.[a-z]+$', basename):
        basename = re.findall(r'^(.*?)\.[a-z]+\.[a-z]+$', basename)[0]
    else:
        basename = os.path.splitext(basename)[0]

    return basename
#------------------------------------------------------------------------------
def BLAST_BESTHITS(target, source, env):
    """
    Get the best hit for each target AA sequence from HMMER3 domain
    table output. The best hit is based on:
    1. min independent e-value
    2. max bitscore
    3. max alignment length
    4. max query coverage at high-scoring segment pair
    """
    blast_names = ['qseqid','sseqid','pident','length','mismatch','gapopen','qstart','qend','sstart','send','evalue','bitscore','ppos','qcovhsp','qseq']

    blasttbl = pd.read_csv(source, comment='#', header=None,
    names = blast_names, sep = '\s+')

    aggregations = {'qseqid':'first', 'evalue':min, 'ppos':max, 'bitscore':max, 'length':max, 'qcovhsp':max}
    blast_agg = blasttbl.groupby(['target_name'], as_index = False).agg(aggregations)

    blast_agg.to_csv(target, sep = '\t', encoding='utf-8', header = True, index = False)
    return None

#Add custom builders to environment
blast_besthit_bld = Builder(action = BLAST_BESTHITS)
builders = {'BLAST_BESTHITS' : blast_besthit_bld}
env.Append(BUILDERS = builders)
#------------------------------------------------------------------------------
TARGETGENES = env['PREFIX'] + '_proteins.faa'
TARGETACC_GENEID = env['PREFIX'] + '_target_hit_accessions.txt'

#Get hits for target gene
env.Command([TARGETACC_GENEID,TARGETGENES], [env['TARGETACC'],env['GFF'],env['SEQFILE']],
"""
grep -f ${SOURCES[0]} ${SOURCES[1]} | \
grep "[[:space:]]CDS[[:space:]]" | \
cut -f10 | \
cut -f1 -d';' | \
cut -f2 -d'=' | \
tee ${TARGETS[0]} | \
pullseq -N -i ${SOURCES[2]} --min %d --max %d > ${TARGETS[1]}
""" % (env['MINLEN'], env['MAXLEN'])
)
#------------------------------------------------------------------------------
#Get hits for surrounding genes
CONTIGPAT='contig_patterns.txt'
env.Command([CONTIGPAT], [env['TARGETACC'],env['GFF'],env['SEQFILE']],
"""
grep -f ${SOURCES[0]} ${SOURCES[1]} | \
grep "[[:space:]]CDS[[:space:]]" | \
cut -f2 | \
uniq | \
awk '{print "[[:space:]]"$0"[[:space:]]"}' | \
sed -e 's/^/\"/g' | \
sed -e 's/$/\"/g' > $TARGET""")

CONGENES = env['PREFIX'] + '_neighbor_genes.faa'

env.Command([CONGENES], [CONTIGPAT,env['GFF'],env['TARGETACC'],env['SEQFILE']],
"""
grep -f ${SOURCES[0]} ${SOURCES[1]} | \
grep "[[:space:]]CDS[[:space:]]" | \
grep -vf ${SOURCES[2]} | \
pullseq -N -i ${SOURCES[2]} --min %d --max %d > $TARGET
""" % (env['MINLEN'], env['MAXLEN'])
)
#------------------------------------------------------------------------------
# #USEARCH dereplicate
# DEREPGENES = env['PREFIX'] + '_derepped.faa'
# env.Command(['all_genes.fasta'], [CONGENES,TARGETGENES], """cat $SOURCES > $TARGET""")
# env.Command([DEREPGENES], ['all_genes.fasta'], """usearch -derep_fulllength $SOURCE -output $TARGET -minseqlength 1 -threads %d""" % env['DMNDTHREAD'])
# logging.info('Run USEARCH dereplicate')
# # #------------------------------------------------------------------------------
# #USEARCH cluster
# CENTROIDS = env['PREFIX'] + '_derepped_cluster_centroids.faa'
# CONSOUT = env['PREFIX'] + '_derepped_cluster_consensus.faa'
# UC = env['PREFIX'] + '_derepped_cluster_results.faa'
# env.Command([CENTROIDS,CONSOUT,UC], [DEREPGENES], """usearch -cluster_fast $SOURCE -id %.2f -centroids ${TARGETS[0]} -consout ${TARGETS[1]} -threads %d -uc ${TARGETS[2]}""" % (env['PCTID'], env['DMNDTHREAD']))
# logging.info('Run USEARCH cluster_fast')
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
#DIAMOND
# DMNDTBL = env['PREFIX'] + '_' + GET_BASENAME(env['DMNDDB']) + '.txt'
#
# blast_outfmt = ['qseqid','sseqid','pident','length','mismatch','gapopen','qstart','qend','sstart','send','evalue','bitscore','ppos','qcovhsp','qseq']
# #MESSING UP HERE
# #env.Command([DMNDTBL], [CONGENES,TARGETGENES,env['DMNDDB']], 'diamond %s --threads %d --db ${SOURCES[2]} --out $TARGET --header --more-sensitive --outfmt 6 %s' % (env['DMNDMETHOD'], env['DMNDTHREAD'], ' '.join(blast_outfmt)))
# diamond_action = 'diamond %s --query ${SOURCES[0]} --threads %d --db ${SOURCES[1]} --out $TARGET --header --more-sensitive --outfmt 6 %s' % (env['DMNDMETHOD'], env['DMNDTHREAD'], ' '.join(blast_outfmt))
# env.Command([DMNDTBL], [DEREPGENES,env['DMNDDB']], diamond_action)

# logging.info('Run DIAMOND')

# #Get best hits
# DMNDBH = env['PREFIX'] + '_' + 'nr' + '_besthit.txt'
# env.BLAST_BESTHITS([DMNDBH], [DMNDTBL])
