AddOption('--build_dir', dest='build_dir', type='string', nargs=1,
action='store', help='root directory for database build')
AddOption('--db', dest='db', type='string', nargs=1,
action='store', help="""Comma-separated list of databases. Choose from:
TIGRFAM,ANTIFAM,PFAM. Use ALL to build all databases.""")

env = Environment(BUILDDIR=GetOption('build_dir'),DB=GetOption('db'))

if ',' in env['DB']:
    env['DB'] = str(env['DB']).split(',')
else:
    pass

##---Databases---###

TIGRDIR = os.path.join(env['BUILDDIR'], 'TIGRFAM')
env.Command('TIGRFAMs_15.0_HMM.tar.gz', '', """mkdir %s && cd %s \
   && wget ftp://ftp.jcvi.org/pub/data/TIGRFAMs/TIGRFAMs_15.0_HMM.tar.gz \
   && tar -zxf $TARGET \
   && rm $TARGET""" % (TIGRDIR, TIGRDIR))

ANTIDIR = os.path.join(env['BUILDDIR'], 'ANTIFAM')
env.Command('Antifam.tar.gz', , """mkdir /build/database/ANTIFAM && cd /build/database/ANTIFAM \
   && wget ftp://ftp.ebi.ac.uk/pub/databases/Pfam/AntiFam/current/Antifam.tar.gz \
   && tar -zxf  $TARGET\
   && rm Antifam.tar.gz""")

# RUN mkdir /build/database/PFAM-A && cd /build/database/PFAM-A \
#    && wget ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam32.0/Pfam-A.hmm.gz \
#    && gunzip Pfam-A.hmm.gz
#
# RUN
